[package]
name = "wealthfolio-core"
version = "1.0.10"
description = "Portfolio tracker"
authors = ["Aziz Fadil"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2.3", features = ["sqlite", "chrono", "numeric", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10.0", features = ["v4"] }
rusqlite = { version = "0.30.0", features = ["bundled"] }
csv = "1.3.0"
yahoo_finance_api = "2.2.1"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["json", "cookies", "cookie_store" ] }
thiserror = "1.0.50"
lazy_static = "1.4.0"
diesel_migrations = { version = "2.1.0", features = ["sqlite" ] }
rayon = "1.8.0"
