[package]
name = "wealthfolio_core"
version = "1.0.11"
description = "Portfolio tracker"
authors = ["Aziz Fadil"]
license = "LGPL-3.0"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
diesel = { version = "2.2.4", features = ["sqlite", "chrono", "r2d2", "numeric", "returning_clauses_for_sqlite_3_35"] }
chrono = { version = "0.4.38", features = ["serde"] }
uuid = { version = "1.10.0", features = ["v4"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
csv = "1.3.0"
yahoo_finance_api = "2.3.0"
regex = "1.10.6"
reqwest = { version = "0.12", features = ["json", "cookies" ] }
thiserror = "1.0.63"
lazy_static = "1.5.0"
diesel_migrations = { version = "2.2", features = ["sqlite" ] }
rayon = "1.10.0"
r2d2 = "0.8.10"
dashmap = "6.1.0"
async-trait = "0.1.83"
bigdecimal = { version = "0.4.5", features = ["serde"] }
num-traits = "0.2"
log = "0.4"