[package]
name = "wealthfolio_core"
version = "1.0.22"
description = "Portfolio tracker"
authors = ["Aziz Fadil"]
license = "AGPL-3.0"
repository = "https://github.com/afadil/wealthfolio"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2", features = ["sqlite", "chrono", "r2d2", "numeric", "returning_clauses_for_sqlite_3_35"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4"] }
rusqlite = { version = "0.32", features = ["bundled"] }
csv = "1.3"
yahoo_finance_api = "2.4"
regex = "1.10"
reqwest = { version = "0.12", features = ["json", "cookies" ] }
thiserror = "1.0"
lazy_static = "1.5"
diesel_migrations = { version = "2.2", features = ["sqlite" ] }
rayon = "1.10"
r2d2 = "0.8"
dashmap = "6.1"
async-trait = "0.1"
bigdecimal = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
log = "0.4"